### ISSUE TITLE
Category search on Service Index 

### ISSUE THREAD

**Issue by cimafrancamae** [TyJacalan/booking-app#58]
Please refer to the attached video for the issues. 

1. Style and responsiveness
2. When I clicked on the categories, the values were concatenated on the search params instead of creating a new search
3. No need to display the category on the search field 

https://github.com/TyJacalan/booking-app/assets/65450522/bf28ac37-6025-44a4-b221-c60048d30813

Suggestion:

Refactor the code below, don't include category links on  the `combined_search` and create a separate ransackable attribute/association for category links
```
<div class="flex flex-wrap gap-2 mb-4">
      <% Category.all.each do |category| %>
        <%= link_to category.title, services_path(q: { combined_search: "#{params.dig(:q, :combined_search)} #{category.title}".strip }), class: "filter-link" %>
      <% end %>
    </div>
```

**Comment by p3rc1us** [comment]
The reason why Categories must be included in the combined_search is so that the client can search **_THROUGH_** the clicked category. I can fix the concatenate but not the Category in combined_search or else clicking the desired Category and typing a search input will not result into succeeded filtering but separate filtering therefore alternating results.
